### ISSUE TITLE
electron-runtime: command not found

### ISSUE THREAD

**Issue by dominicpaul1911** [sentialx/electron-global#2]
Since I had already installed electron builder, installed only electron runtime using this 
`npm install --save-dev electron-runtime` and updated package.json script as `"dist": "electron-runtime -m && electron-builder -m"`

When i run npm run dist, I get electron-runtime command not found. Electron Builder works fine. 

Am I missing something?

**Comment by sentialx** [comment]
Hi, sorry I haven't published `electron-runtime` to npm yet. It also seems the name is already taken, I guess I will need to change it to `electron-global`. Thanks!

**Comment by sentialx** [comment]
@dominicpaul1911 Try to install `electron-global`. I've recently published a 0.0.1 release.
