### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Armaldio** [sentialx/electron-global#3]
*I have a little understanding of how it work internally*

I remember having cache (localstorage, cookies, etc..) issues when sharing electron binaries 
How do you handle that?

**Comment by sentialx** [comment]
As of my knowledge, Electron automatically creates a user data folder basing on the `package.json` `name` field.

**Comment by Armaldio** [comment]
Ah, so as long as I've different names, there will not be any conflicts?
That may indeed be my problem with my testing (copy pasting projects)
