### ISSUE TITLE
"build" section in package.json cause ignore electron-global to run in build process.

### ISSUE THREAD

**Issue by eAmin** [sentialx/electron-global#7]
I need to use "build" section in package.json file to customize electron-builder output. But when i use "build" section in package.json, electron-global never be invoked.

Here is with "build" section messages:
```
  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=5.0.10 appOutDir=release\win-unpacked
  • default Electron icon is used reason=application icon is not set
  • building        target=nsis file=release\Setup 2.0.0.exe archs=x64 oneClick=false perMachine=true
  • building block map blockMapFile=release\Setup 2.0.0.exe.blockmap
```

Without "build" section:
```
 • electron-builder version=20.44.4
  • loaded configuration file=C:\Users\...\electron-builder.json
  • writing effective config file=dist\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=5.0.10 appOutDir=dist\win-unpacked
  • copying Electron source=C:\Users\...\electron-global destination=C:\Users\...\dist\win-unpacked
```
You'll see "copying Electron..." and it means now invoked electron-global.
Is this a bug or something else?

Env: Win10-x64 build 1903 latest update, node 12.10.0, and please don't mind electron-builder version :)

**Comment by eAmin** [comment]
Any progress?

**Comment by sentialx** [comment]
Unfortunately I can't reproduce

**Comment by eAmin** [comment]
I will do that tonight

**Comment by eAmin** [comment]
@sentialx I made a branch from electron-quick-start, you can clone and run the codes:

```
git clone -b electron-global https://github.com/eAmin/electron-quick-start.git
cd electron-quick-start
```


Then run the following command:
```
npm i
npm run build:render
npm run build
```

If you run that commands, you will see electron-global does not invoked by electron-builder and that builder do the own work and installer with electron bundle with more than 40MB file size created in "release" folder. But if you delete these lines from package.json:
```javascript
  "build": {
    "productName": "Electron Global",
    "appId": "org.electron.global",
    "files": [
      "build/",
      "package.json",
      "main.js"
    ],
    "win": {
      "target": [
        "nsis"
      ]
    },
    "directories": {
      "output": "release"
    }
  },
```
Then do the same build process, and you will see the installer created without electron bundled exe file with less than 2MB file size in dist folder (if doesn't work delete all release build and dist folder and do build process again).

Thanks.

**Comment by sentialx** [comment]
@eAmin You didn't set `electronDist` property as stated [here](https://github.com/sentialx/electron-global#usage).

**Comment by eAmin** [comment]
@sentialx Actually I did it, look at electron-global branch please :)

https://github.com/eAmin/electron-quick-start/tree/electron-global
https://github.com/eAmin/electron-quick-start/blob/electron-global/electron-builder.json

**Comment by sentialx** [comment]
`electron-builder` doesn't respect multiple configs at once, so you have to specify `electronDist` in the `package.json`

```
 "build": {
    "electronDist": "./electron-global",
    "productName": "Electron Global",
    "appId": "org.electron.global",
    "files": [
      "build/",
      "package.json",
      "main.js"
    ],
    "win": {
      "target": [
        "nsis"
      ]
    },
    "directories": {
      "output": "release"
    }
  },
```

**Comment by eAmin** [comment]
Oh thanks, I will test it and let's see what's happened.
